[package]
name = "enet"
version = "0.1.0"
authors = ["Felix Rath <felixm.rath@gmail.com>"]
edition = "2018"

[dependencies]
enet-sys = "0.2.1"
failure = "0.1.2"
failure_derive = "0.1.2"
byteorder = "1.2.6"
lazy_static = "1.1.0"
